# Generated by Django 4.0.6 on 2023-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_enddaydailyreport_beverage_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='loyalty_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
