# Generated by Django 4.0.6 on 2024-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_loyalty_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='end_day_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
