# Generated by Django 4.0.6 on 2023-10-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_customerproduct_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Bud Title')),
                ('slug', models.SlugField(null=True, verbose_name='Bud Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Bud Description')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='cbd_content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='thc_content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='budclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.budclass'),
        ),
    ]
