# Generated by Django 4.0.6 on 2023-10-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_budclass_product_cbd_content_product_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
    ]
