# Generated by Django 4.0.6 on 2023-10-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='budclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.budclass'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
