# Generated by Django 4.0.6 on 2023-10-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_budclass_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budclass',
            name='bag_1_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budclass',
            name='bag_2_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budclass',
            name='bag_3_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budclass',
            name='bag_4_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budclass',
            name='bag_5_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budclass',
            name='bag_6_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budclass',
            name='bag_7_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='budclass',
            name='bag_8_price',
            field=models.FloatField(default=0.0),
        ),
    ]
