# Generated by Django 4.0.6 on 2023-10-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_budclass_bag_1_price_budclass_bag_2_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
