# Generated by Django 4.0.6 on 2023-10-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_taxbracket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxbracket',
            old_name='tax_amount',
            new_name='tax_percent',
        ),
    ]
