# Generated by Django 4.0.6 on 2023-10-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_tax_amount_taxbracket_tax_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxbracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.taxbracket'),
        ),
    ]
