# Generated by Django 4.0.6 on 2023-10-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_taxbracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbracket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tax Description'),
        ),
    ]
