# Generated by Django 4.0.6 on 2023-10-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_taxbracket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cbd_content',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='thc_content',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
