# Generated by Django 4.0.6 on 2023-11-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_loyalty_points'),
        ('product', '0017_productpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductPointsTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('starting_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('remaining_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_no', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
