# Generated by Django 4.0.6 on 2024-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_customerproductpointstrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_menu_item',
            field=models.BooleanField(default=True),
        ),
    ]
