# Generated by Django 4.0.6 on 2023-10-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_alter_tablreturnentry_notaxsales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_end_day',
            field=models.BooleanField(default=False),
        ),
    ]
