# Generated by Django 4.0.6 on 2023-12-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_loyalty_points'),
        ('product', '0018_customerproductpointstrack'),
        ('bill', '0008_bill_is_end_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbldeliveryhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('deliveryDate', models.DateTimeField(blank=True, null=True)),
                ('deliver_to', models.CharField(blank=True, max_length=200, null=True)),
                ('special_request', models.CharField(blank=True, max_length=200, null=True)),
                ('Current_state', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_option', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tbldelivery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deliveryHistoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.tbldeliveryhistory')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
