# Generated by Django 4.0.6 on 2023-12-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_tbldeliveryhistory_tbldelivery_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldeliveryhistory',
            name='Current_state',
            field=models.CharField(default='Ordered', max_length=200),
        ),
    ]
