# Generated by Django 4.0.6 on 2023-12-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_alter_tbldeliveryhistory_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldeliveryhistory',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.bill'),
        ),
        migrations.AddField(
            model_name='tbldeliveryhistory',
            name='bill_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
