# Generated by Django 4.0.6 on 2024-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_tbldeliveryhistory_bill_tbldeliveryhistory_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
