# Generated by Django 4.0.6 on 2023-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customernormallogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernormallogin',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
