# Generated by Django 4.0.6 on 2023-12-18 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customernormallogin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernormallogin',
            name='reset_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='customernormallogin',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
