# Generated by Django 4.0.6 on 2023-07-28 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubledger',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.accountledger'),
        ),
    ]
